services:
  questflag.infrastructure.services:
    image: ${DOCKER_REGISTRY-}questflaginfrastructureservices
    build:
      context: ..
      dockerfile: Infrastructure/QuestFlag.Infrastructure.Services/Dockerfile
