services:
  service-qf-infra:
    image: ${DOCKER_REGISTRY-}questflaginfrastructureservices
    build:
      context: ..
      dockerfile: Infrastructure/QuestFlag.Infrastructure.Services/Dockerfile
  app-qf-passport:
    image: ${DOCKER_REGISTRY-}questflagpassportwebapp
    build:
      context: ..
      dockerfile: Passport/QuestFlag.Passport.WebApp/QuestFlag.Passport.WebApp/Dockerfile
  app-qf-passport-admin:
    image: ${DOCKER_REGISTRY-}questflagpassportadminwebapp
    build:
      context: ..
      dockerfile: Passport/QuestFlag.Passport.AdminWebApp/QuestFlag.Passport.AdminWebApp/Dockerfile
